### ISSUE TITLE
setup dynamo db

### ISSUE THREAD

**Issue by enriquezrene** [ioet/bpm-people#12]
Set up dynamo db and create a table to manage the basic data for people including the following fields:
Name
Lastname
Email
Address (Optional)
ZIP Code (Optional)

**Comment by ralden** [comment]
That schema, Address/ZIP code is not suitable (conforms to no known international standard :) ), but we don't really need it now.

Name, Last name also fails the international schema test (see the spec :) ).

And something is missing, we need a guid.

**Comment by enriquezrene** [comment]
Table is created and a new group called bpm_people was created to give permissions to any user, for now it has a policy to do anything using Dynamo, later we need to re-define the policies file.
